### ISSUE TITLE
Is it possible to do fuzzy-search with this addon? 

### ISSUE THREAD

**Issue by collegeimprovements** [gmurphey/ember-search-helper#5]

**Comment by gmurphey** [comment]
It isn't possible yet. What kind of fuzzy search are you hoping to use? This may be something we're interested in supporting.

**Comment by Luiz-N** [comment]
[fusejs](http://fusejs.io/) seems to be the most "popular" one.

That might be overkill though. This ["fuzzy lib"](https://github.com/mattyork/fuzzy) looks like it would be simple to drop in although you'd have to do a custom function if an array of objects is used.
